### ISSUE TITLE
metrics-server-deployment.yamlが無いというエラー

### ISSUE THREAD

**Issue by Shi9eru** [takara9/vagrant-kubernetes#10]
ご著作にて勉強させていただいております。Docker初学者にもわかりやすい本をありがとうございます。
Windows環境にてvagrant-kubernetesの1.14を用いてvagrant upをしたのですが、以下のメッセージが現れてエラーとなってしまいます。

↓↓↓
TASK [add a new line] **********************************************************
fatal: [master]: FAILED! => {"changed": false, "msg": "Path /home/vagrant/metrics-server/deploy/kubernetes/metrics-server-deployment.yaml does not exist !", "rc": 257}

PLAY RECAP *********************************************************************
master                     : ok=17   changed=13   unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
↑↑↑

metrics-server-deployment.yamlというファイルが所定の場所に無いというエラーのようなのですが、解決するための方法をご教示いただけますと幸いです。

どうぞよろしくお願い申し上げます。

**Comment by takara9** [comment]
再現テストをしてみました。残念ながら、ご指摘以前の問題もあるようです。
解決策を考えてみますので、１~２周間くらい、お時間をください。

**Comment by Shi9eru** [comment]
ありがとうございます。
手厚いご対応に感謝です。

**Comment by takara9** [comment]
調べた結果、Ansible Playbookの問題ではなく、利用しているYAMLのリポジトリや、コンテナレジストリの問題の様です。今夜、試したところ、問題なく動作しました。　オープンソースのプロジェクトは、それぞれ、独自に活動しているので、リポジトリがメンテナンスでアクセスできなくなったり、修正間違えで動かなくなることもあるので、もし、動かない時は、しばらく時間を置いてから、リトライすると良い様です。それでも、動作しなければ、Issueに挙げて頂ければと思います。

**Comment by Shi9eru** [comment]
私のほうでもうまくいきました！
ありがとうございます！
