### ISSUE TITLE
master nodeにてMetrics Serverのインストールエラー

### ISSUE THREAD

**Issue by camohi** [takara9/vagrant-kubernetes#5]
`vagrant up`において下記のエラーが出ております。

```
TASK [master : add a new line] *************************************************
fatal: [master]: FAILED! => {"changed": false, "msg": "Path /home/vagrant/metrics-server/deploy/kubernetes/metrics-server-deployment.yaml does not exist !", "rc": 257}

PLAY RECAP *********************************************************************
master                     : ok=35   changed=29   unreachable=0    failed=1    skipped=19   rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

[gitのREADME.md](https://github.com/kubernetes-sigs/metrics-server/blob/master/README.md)を参照すると、manifest fileのパスがまたもや変わっているようです。

![image](https://user-images.githubusercontent.com/25682298/80897553-ef403600-8d34-11ea-903b-a6c9c77a5bf3.png)

masterのyamlファイルで、metrics serverの部分を少々変更する必要がある認識です。
対応策を私も調べてみますが、お時間ありましたら対応をお願いします。

**Comment by takara9** [comment]
Issueに挙げていただき、ありがとうございます。別件でもMetrics Serverのコードの変更により不具合があり、対策を考えているところでした。追って、こちらにも対応しますので、少し、時間を頂ければ幸いです。

**Comment by takara9** [comment]
@hisatohayashi さん、

問題に対する修正をmasterブランチの https://github.com/takara9/vagrant-kubernetes/commit/e2f68afa01ff09fb8e983734979147d1d432dfb1 で施しました。

これで、git pull するか、あらためて git clone してもらって、vagrant upで k8sクラスタが起動できると思います。ご確認頂ければ幸いです。それから、masterブランチ以外は未対応です。 他のブランチでは 1.18 のみ対応予定です。

**Comment by takara9** [comment]
その後、問題無ければ、1日後にCloseさせていただきます。

**Comment by camohi** [comment]
@takara9 さん、修正版で正常に環境構築が完了いたしました。ありがとうございました。こちらでクローズいたします。
