### ISSUE TITLE
「15Stepで習得Dockerから入るKubernetes」の学習環境２(P.490あたり）のProxy配下での構築について

### ISSUE THREAD

**Issue by rakinamini** [takara9/vagrant-kubernetes#8]
windows10pro上で、P.490当たりの学習環境２の構築をProxy配下で行っております。
以下2点のProxy設定の対応(*)は行っているのですが、TASK [kubernetes : Add GlusterFS Repository]ところでエラーがでます。
他のサイトで調べると、
--keyserver-optionというものを使えば解決できそうな気がしています。
--keyserver-option http-proxy=http://プロキシサーバ:ポート
この設定でよいのか、この設定をどこに入れればご教示いただけないでしょうか。

（＊）
★gitのproxy設定
git config --global http.proxy http://<proxyserver>:<port>
git config --global https.proxy http://<proxyserver>:<port>
★vagrant向けのproxy設定　環境変数
set http_proxy=http://{proxy_ip}:{proxy_port}
set https_proxy=http://{proxy_ip}:{proxy_port}

■ログ
C:\Users\windows_username\vagrant-kubernetes>vagrant up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'node1' up with 'virtualbox' provider...
Bringing machine 'node2' up with 'virtualbox' provider...
==> master: Importing base box 'ubuntu/bionic64'...
==> master: Matching MAC address for NAT networking...
==> master: Checking if box 'ubuntu/bionic64' version '20210928.0.0' is up to date...
==> master: A newer version of the box 'ubuntu/bionic64' for provider 'virtualbox' is
==> master: available! You currently have version '20210928.0.0'. The latest is version
==> master: '20211021.0.0'. Run `vagrant box update` to update.
==> master: Setting the name of the VM: vagrant-kubernetes_master_1634904642536_96830
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 22 (guest) => 2222 (host) (adapter 1)
==> master: Running 'pre-boot' VM customizations...
==> master: Booting VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2222
    master: SSH username: vagrant
    master: SSH auth method: private key
    master: Warning: Connection reset. Retrying...
    master: Warning: Connection aborted. Retrying...
    master: Warning: Remote connection disconnect. Retrying...
    master: Warning: Connection aborted. Retrying...
    master: Warning: Connection reset. Retrying...
    master: Warning: Remote connection disconnect. Retrying...
    master:
    master: Vagrant insecure key detected. Vagrant will automatically replace
    master: this with a newly generated keypair for better security.
    master:
    master: Inserting generated public key within guest...
    master: Removing insecure key from the guest if it's present...
    master: Key inserted! Disconnecting and reconnecting using new SSH key...
==> master: Machine booted and ready!
==> master: Checking for guest additions in VM...
    master: The guest additions on this VM do not match the installed version of
    master: VirtualBox! In most cases this is fine, but in rare cases it can
    master: prevent things such as shared folders from working properly. If you see
    master: shared folder errors, please make sure the guest additions within the
    master: virtual machine match the version of VirtualBox you have installed on
    master: your host and reload your VM.
    master:
    master: Guest Additions Version: 5.2.42
    master: VirtualBox Version: 6.0
==> master: Setting hostname...
==> master: Configuring and enabling network interfaces...
==> master: Configuring proxy for Apt...
==> master: Configuring proxy environment variables...
==> master: Configuring proxy for Git...
==> master: Mounting shared folders...
    master: /vagrant => C:/Users/windows_username/vagrant-kubernetes
==> master: Detected mount owner ID within mount options. (uid: 1000 guestpath: /vagrant)
==> master: Detected mount group ID within mount options. (gid: 1000 guestpath: /vagrant)
==> master: Running provisioner: ansible_local...
    master: Installing Ansible...
    master: Running ansible-playbook...

PLAY [Kubernetes base] *********************************************************

TASK [Gathering Facts] *********************************************************
ok: [master]

TASK [kubernetes : Change selinux] *********************************************
skipping: [master]

TASK [kubernetes : Stop firewalld] *********************************************
skipping: [master]

TASK [kubernetes : Disable Swap area and delete] *******************************
skipping: [master]

TASK [kubernetes : Add Docker GPG key] *****************************************
changed: [master]

TASK [kubernetes : Add Docker APT repository] **********************************
changed: [master]

TASK [kubernetes : Install a list of packages] *********************************
changed: [master]

TASK [kubernetes : ensure a list of packages uninstalled] **********************
skipping: [master]

TASK [kubernetes : Add Docker repository] **************************************
skipping: [master]

TASK [kubernetes : ensure a list of packages installed] ************************
skipping: [master]

TASK [kubernetes : Add the user 'vagrant' with a specific uid and a primary group of 'docker'] ***
changed: [master]

TASK [kubernetes : Start dockerd] **********************************************
ok: [master]

TASK [kubernetes : Add GlusterFS Repository] ***********************************
fatal: [master]: FAILED! => {"changed": false, "cmd": "apt-key adv --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 F7C73FCC930AC9F83B387A5613E01B7B3FE869A9", "msg": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: keyserver receive failed: Connection timed out", "rc": 2, "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: keyserver receive failed: Connection timed out\n", "stderr_lines": ["Warning: apt-key output should not be parsed (stdout is not a terminal)", "gpg: keyserver receive failed: Connection timed out"], "stdout": "Executing: /tmp/apt-key-gpghome.T1qMlNh4LI/gpg.1.sh --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 F7C73FCC930AC9F83B387A5613E01B7B3FE869A9\n", "stdout_lines": ["Executing: /tmp/apt-key-gpghome.T1qMlNh4LI/gpg.1.sh --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 F7C73FCC930AC9F83B387A5613E01B7B3FE869A9"]}

PLAY RECAP *********************************************************************
master                     : ok=6    changed=4    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

C:\Users\windows_username\vagrant-kubernetes>

**Comment by takara9** [comment]
Ansibleの以下のドキュメントが参考になるのではと思います。
https://docs.ansible.com/ansible/2.9_ja/user_guide/playbooks_environment.html

**Comment by rakinamini** [comment]
アドバイスありがとうございます。
まだためてせていませんが、リンクを参考に対応させていただきます。

**Comment by rakinamini** [comment]
いろいろ試行錯誤しましたが、うまくいきませんでした。書籍の範囲外ということでいったんCLOSEさせていただきます。
