### ISSUE TITLE
nodeの増減設がやりたいのです。

### ISSUE THREAD

**Issue by Kon-y** [takara9/vagrant-kubernetes#9]
良いコードありがとうございます。k8s環境が簡単に作れました。
インフラエンジニアとしてk8s-nodeの増減設をやってみたいのですが、このソースを使ってやるにはどのようにすればよいでしょうか。ご教示いただけますと幸甚です。

**Comment by takara9** [comment]
ノードの増設 ansible の増設task、vagrant の ノード増設を作ってあげる必要があります。

開発のヒントとしては、
ノード増設では、Vagrantfile に追加するノードを記述した後、追加ノードで、Ansibleの増設用のタスクを走らせることになります。
https://github.com/takara9/vagrant-kubernetes/tree/master/playbook/node/tasks/main.yml　の中の kubeadmin join を 追加ノードで実行することで増やせます。

ノードの削減は、ノードからポッドを退避した後の kubectl delete no ＜削除対象ノード名＞
vagrant stop node などで、ノードを停止すると良いでしょう。

**Comment by Kon-y** [comment]
ご回答ありがとうございました。
